export enum LoginResponseStatus {
  SUCCESS = "SUCCESS",
  FAILURE = "FAILURE",
  INVALID_USERNAME_AND_PASSWORD = "INVALID_USERNAME_AND_PASSWORD",
  USER_INACTIVE = "USER_INACTIVE",
  USER_LOCKED = "USER_LOCKED",
  CUSTOMER_LOCKED = "CUSTOMER_LOCKED",
  CUSTOMER_INACTIVE = "CUSTOMER_INACTIVE",
  INVALID_DEVICE_ID = "INVALID_DEVICE_ID",
  DEVICE_ID_NOT_FOUND = "DEVICE_ID_NOT_FOUND",
  INVALID_DEVICE_FOR_USER = "INVALID_DEVICE_FOR_USER",
}
